workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    APImetrics:
        inputs:
            - location: /tmp/openapi.json
        overlays:
            - location: .speakeasy/globals.overlay.yaml
        transformations:
            - removeUnused: true
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/apicontext-qpv/test-workspace/ap-imetrics
targets:
    apimetrics:
        target: cli
        source: APImetrics
